name: robot
description: ""
ports: []
bricks:
- arduino:web_ui: {}
- arduino:arduino_cloud:
    variables:
      ARDUINO_DEVICE_ID: xxx
      ARDUINO_SECRET: yyy
- arduino:video_object_detection:
    model: yolox-object-detection
icon: 🛻
